### ISSUE TITLE
このGitHubページへのリンクがドキュメント内に欲しい

### ISSUE THREAD

**Issue by take-w** [tork-a/tork_moveit_tutorial#13]
印刷冊子には、このGitHubページへのリンクが書かれていない。
したがって（実はこのGitHubページから印刷冊子が作られていることを知らない人は）
実行コード例を手で打ち込むのが大変＆ミスるかもしれない。
このGitHubページへのリンク
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/index.md
を明記して、読者がコピペ実行できるようにするとよいと思います。

**Comment by 7675t** [comment]
ご指摘ありがとうございます． #14 #15 #16 ともども修正します．
