### ISSUE TITLE
ライセンス表示

### ISSUE THREAD

**Issue by take-w** [tork-a/tork_moveit_tutorial#14]
印刷冊子の pp. 101-103 では、
このドキュメント全体のライセンス表示をしたいはずだが、
フッターが 7.3., Chapetr 7. （←Pythonの章）になっている。

**Comment by 7675t** [comment]
@k-okada これ，ちょっと直す方法がわかりません．

**Comment by k-okada** [comment]
#22 で対応したつもりです．確認してみてください．
