### ISSUE TITLE
誤字・脱字・不自然な日本語表現など

### ISSUE THREAD

**Issue by take-w** [tork-a/tork_moveit_tutorial#15]
【１】
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_introduction.md
1段落目
　× 初められる
　○ 始められる

【２】
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_robot-simulator.md
ページ中央の「時間がかかります場合が有ります」で
『かかります』は『かかる』の方が自然。

【３】
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_robot-python_advanced.md
ページ下方の「の X軸 は 3.1415 として」で
最初の『の』は不要。

【４】
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_reference-class-functions.md
def go
　×まつか否か
　○待つか否か
def def name(self)
　defが一個多い？
def attach_box
　×箱ブジェクト
　○箱オブジェクト

**Comment by k-okada** [comment]
Closed via #17
