### ISSUE TITLE
リンク先・リンク文字列の不正

### ISSUE THREAD

**Issue by take-w** [tork-a/tork_moveit_tutorial#16]
【A】
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_introduction.md
の下にあるリンク2つ
Python チュートリアル - その1
Python チュートリアル - その2
（https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_python-basic.md
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_python-advanced.md）
が切れている。
このリンク2つは
Python チュートリアル
（https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_python.md）
1つにすべき。

【B】
https://github.com/tork-a/tork_moveit_tutorial/blob/indigo-devel/doc/moveit-tutorial_ja_robot-simulator.md
Baxter ソフトウェアのインストール　節の二つ目のリンクの文字列
×http://sdk.rethinkrobotics.com/wiki/Workstation_Setup
○http://sdk.rethinkrobotics.com/wiki/Simulator_Installation

**Comment by k-okada** [comment]
@take-w ありがとうございます．
typoみたいなものは以下のようにブラウザ上から直接変更してpull requestを送れますので，ぜひ試していただけると嬉しいです．

![output](https://user-images.githubusercontent.com/493276/51538483-c2944200-1e94-11e9-9db3-183c7e6d9b84.gif)

**Comment by k-okada** [comment]
【A】 の方は未対応

**Comment by k-okada** [comment]
Closed via #17
