### ISSUE TITLE
ROS biginner!  Cannot use rosrun!  

### ISSUE THREAD

**Issue by rockyist** [tork-a/tork_moveit_tutorial#48]
I am a beginner of ROS and also engineering itself, but try to handle ROS and MOVEIt.  

I use tutorials at the following site.
http://moveit2_tutorials.picknik.ai/

I finished to setup Ubuntu 20 and ROS noetic to my PC.  I finished 'Getting started' and 'MoveIt Quickstart in RViz' on this web site.

I then went to 'Pick and Place'.  
I finished,
"roslaunch panda_moveit_config demo.launch"
and it was OK.

But I opened second terminal and loaded just as this tutorial instructed,
"rosrun moveit_tutorials pick_place_tutorial"
but, it replied, 'Cannot find command 'rosrun'.  You can install it in following way:  
sudo apt install rosbash

but it cannot go well.  The message says, there are package(s) that could not be installed.  
It also says that some packages (that are not forbidden to change) are already broken.

What should be the root cause for this?

What should I do?

If you understand this situation and have any good idea, please advise me what to do.
Thanks,

**Comment by y-yosuke** [comment]
Did you set your ROS1 environment on a new terminal before you execute `rosrun`?

```
$ source /opt/ros/noetic/setup.bash
```

or when you have your own ROS1 workspace,
( Please change `PATH_TO_YOUR_WORKSPACE` to your ROS1 workspace path )

```
$ source PATH_TO_YOUR_WORKSPACE/devel/setup.bash
``` 

And this repository is different from the repository of the tutorial that you are practicing.
The repository of the tutorial you are practicing is linked below.

https://github.com/ros-planning/moveit2_tutorials/issues

If you have questions about the contents, I recommend that you ask questions to the Issues there.

**Comment by rockyist** [comment]
y-yosuke 様

こんなに早くコメントを下さり、感謝いたします。日本語で解答いただけると知らなかったので、英語で質問させていただきましたが、日本語で質問したいと思います。

2つターミナルを開いて２つ目で、
rosrun moveit_tutorials pick_place_tutorial

をロードしましたが、下記のようなエラーがでました。

<img width="317" alt="cannot go" src="https://user-images.githubusercontent.com/49644055/123796164-cb1fbb00-d91f-11eb-9639-6f1f942b1de4.PNG">

<img width="321" alt="cannot go2" src="https://user-images.githubusercontent.com/49644055/123796187-d1ae3280-d91f-11eb-8d03-8ae63446c09e.PNG">

もし可能でしたら、日本語でアドバイスいただけませんでしょうか？

よろしくお願いいたします。

**Comment by y-yosuke** [comment]
英語で書いたことと同じことになるのですが，1つ目のターミナルで `roslaunch` が実行できて，2つ目のターミナルで `rosrun` が見つからず実行できない場合に最初に確認すべき点は2つ目のターミナルで ROS の環境設定を行っていないで `rosrun` のコマンドへのパスが通っていないことです．

- Environment setup
  - http://wiki.ros.org/noetic/Installation/Ubuntu#noetic.2FInstallation.2FDebEnvironment.Environment_setup

ROS 環境設定はターミナルを新規ウィンドウでも新規タブでも起動するごとに設定する必要があります．

```
$ source /opt/ros/noetic/setup.bash
```

もしくは ROS1 のワークスペース内で実行しているなら

```
$ source PATH_TO_YOUR_WORKSPACE/devel/setup.bash
```

この ROS 環境設定が出来ているかを確認するにはターミナルで `env | grep ROS` とすると ROS の文字を含む環境設定が表示されてきちんとパスが通っているかが確認できます．

```
$ env | grep ROS
```

（次の投稿で `env | grep ROS` の実行例を提示します．）

パスが通っていれば `rosrun` も実行できると思うのですが，ROS 環境をしているかどうかを確認いただけたらと思います．

**Comment by y-yosuke** [comment]
ROS 環境設定をして環境パスが通っている状態の例（パスが通っている先がより多いこともあります）

```bash
robotuser@robotuser-PC:~$ source /opt/ros/noetic/setup.bash
robotuser@robotuser-PC:~$ env | grep ROS
ROS_VERSION=1
ROS_PYTHON_VERSION=3
ROS_PACKAGE_PATH=/opt/ros/noetic/share
ROSLISP_PACKAGE_DIRECTORIES=
ROS_ETC_DIR=/opt/ros/noetic/etc/ros
ROS_MASTER_URI=http://localhost:11311
ROS_ROOT=/opt/ros/noetic/share/ros
ROS_DISTRO=noetic
```

新しいターミナルを起動して ROS 環境を設定ていない場合の `env | grep ROS` の結果例（ROS へのパスの設定が無い状態）

```bash
robotuser@robotuser-PC:~$ env |grep ROS
robotuser@robotuser-PC:~$ 
```

**Comment by rockyist** [comment]
お世話になっております。

やってみました。
<img width="416" alt="20210630" src="https://user-images.githubusercontent.com/49644055/123908579-ab85a280-d9b2-11eb-97a5-662e31d594fd.PNG">

ROS環境設定はできてパスが通っているようなのですが、rosrunができない、です。まだ。

どうしたらいいでしょうか？
お忙しいところ、すみません。

よろしくお願いいたします。

**Comment by y-yosuke** [comment]
環境設定が正しいようでしたらメッセージどおりに rosbash をインストールしてみるとどうなりますでしょうか？

システム環境は Ubuntu 20.04 + ROS Noetic でしたら，次のようにして 頭に `ros-noetic-` をつけて rosbash をインストールできると思います．

```
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install ros-noetic-rosbash
```

- How to install rosbash in ros-noetic ?
  - https://answers.ros.org/question/353177/how-to-install-rosbash-in-ros-noetic/

**Comment by rockyist** [comment]
y-yosuke様

お世話になっております。

$ sudo apt update
$ sudo apt upgrade
$ sudo apt install ros-noetic-rosbash

上記３つを問題なくロードできたようです。でも、rosrunができない。なぜか？

すみません、あまり、知識がなくて。Linuxのコマンドについても始めたばかりなので詳しくなくて。勉強します。

何か、rosrunできるようにしたいですが。どうしたらいいでしょうか？

または、下記に私がしたものの写真をはりますので、何かおかしなことをしていないか、見ていただけないでしょうか？

<img width="369" alt="20210630_rosbash" src="https://user-images.githubusercontent.com/49644055/123926603-fdd0be80-d9c6-11eb-9ed9-6da66bb9133c.PNG">
<img width="359" alt="20210630_upgrade" src="https://user-images.githubusercontent.com/49644055/123926635-07f2bd00-d9c7-11eb-9968-b6b806d9316d.PNG">
<img width="366" alt="20210630_rosupgrade3" src="https://user-images.githubusercontent.com/49644055/123926695-1a6cf680-d9c7-11eb-8eca-86eed08a243a.PNG">

**Comment by rockyist** [comment]
これもありました。

<img width="376" alt="20210630_sudoaptinstallrosnoeticrosbash" src="https://user-images.githubusercontent.com/49644055/123927573-f1993100-d9c7-11eb-8ea4-056a39f8e28d.PNG">

**Comment by y-yosuke** [comment]
`rosrun` へのパスは通っていそうですがパッケージ `moveit_tutorials` が見つからないので実行できない状況に見えます．

あと英語での投稿 https://github.com/tork-a/tork_moveit_tutorial/issues/48#issuecomment-870408889 を読んでいただけたらと思ったのですが，
`PATH_TO_YOUR_WORKSPACE` は各自のワークスペースへのディレクトリパスで置き換えてください．

> or when you have your own ROS1 workspace,
> ( Please change PATH_TO_YOUR_WORKSPACE to your ROS1 workspace path )
> 
> ```
> $ source PATH_TO_YOUR_WORKSPACE/devel/setup.bash
> ```

またパッケージ `moveit_tutorials` はここの Issue のパッケージ `tork_moveit_tutorial` とは別ですので 
`moveit_tutorials` のインストールやパッケージパスがどこかについては，そちらのチュートリアルを見返していただくか，
パッケージ `moveit_tutorials` で Issue を立てていただけたらと思います．

- http://moveit2_tutorials.picknik.ai/
- https://github.com/ros-planning/moveit_tutorials
- https://github.com/ros-planning/moveit2_tutorials

> And this repository is different from the repository of the tutorial that you are practicing.
> The repository of the tutorial you are practicing is linked below.
> 
> https://github.com/ros-planning/moveit2_tutorials/issues
> 
> If you have questions about the contents, I recommend that you ask questions to the Issues there.

**Comment by rockyist** [comment]
y_yousuke様

お世話になります。
できました。
教えていただいたように、ワークスペースで、
$ source PATH_TO_YOUR_WORKSPACE/devel/setup.bash

と入力したときに、この前は、自分のワークスペースの名前だけ書いたのですが、今回は、友人に教えてもらい、~/自分のワークスペース/devel/setup.bash
としたら、問題なく、rosrunができました。（~/が抜けていました。自分のワークスペースへの通し方がわからなかったのですね。）

解決しました。ありがとうございました。

**Comment by y-yosuke** [comment]
解決して何よりです．
